title:            Dev Blog
description:      A bunch of thoughts
url:              http://blog.piklus.con
signoff:          Grzegorz Łuszczek
disqus_shortname: grzlus
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         GitHub
    url:          http://github.com/grzlus
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
